[project]
name = "comfyui-pixtral"
description = "For loading and running Pixtral models"
version = "1.0.0"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/SeanScripts/ComfyUI-Pixtral"
#  Used by Comfy Registry https://comfyregistry.org 

[tool.comfy]
PublisherId = "seanscripts"
DisplayName = "ComfyUI-Pixtral"
Icon = ""
